// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoscowInstitute.InfrastructureServices.Gateways.Database;

namespace MoscowInstitute.WebService.Migrations
{
    [DbContext(typeof(InstituteContext))]
    [Migration("20200604002545_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("MoscowInstitute.DomainObjects.Institute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChiefName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebSite")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Institutes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ChiefName = "Ледовская Татьяна Леонидовна",
                            LegalAddress = "123154, ГОРОД МОСКВА, УЛИЦА МАРШАЛА ТУХАЧЕВСКОГО, 20, 1",
                            ShortName = "ГБОУ ДО ДТДМ «Хорошево»",
                            WebSite = "dtim.mskobr.ru"
                        },
                        new
                        {
                            Id = 2L,
                            ChiefName = "Шпаро Матвей Дмитриевич",
                            LegalAddress = "109147, г. Москва, ул. Нижегородская, д. 3",
                            ShortName = "ГБУ «Лаборатория путешествий»",
                            WebSite = "lab-putesh.mskobr.ru"
                        },
                        new
                        {
                            Id = 3L,
                            ChiefName = "Седова Наталья Николаевна",
                            LegalAddress = "115569, г. Москва, Шипиловский проезд, дом 37, корпус 1",
                            ShortName = "ГБПОУ колледж «Царицыно»",
                            WebSite = "collegetsaritsyno.mskobr.ru"
                        },
                        new
                        {
                            Id = 4L,
                            ChiefName = "Коминова Елена Борисовна",
                            LegalAddress = "107553, Москва, ул. Большая Черкизовская, д. 15",
                            ShortName = "ГБОУДО «ДТДиМ «Преображенский»",
                            WebSite = "dtdimvouo.mskobr.ru"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
